server:
  # 端口
  port: 8002
  # 服务
  servlet:
    # 服务名
    context-path: /

spring:
      application:
          name: file-system
      profiles:
          active: prd
###########################################################################

########################################################################
# 分页插件 pagehelper
pagehelper:
  # 数据库类型
  helper-dialect: mysql
  # 其他一些配置
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
  pageSizeZero: true

